### ISSUE TITLE
documentation missing

### ISSUE THREAD

**Issue by coffebar** [ikrivosheev/acpi-backlight-notify#1]
https://github.com/ikrivosheev/acpi-backlight-notify/assets/3100053/d99f0c60-7470-4b41-b3ea-651339457837

Don't understand how to use this or it's not working.

With started daemon I change the brightness and see no notifications.

i3wm arch. The notification daemon is Dunst.

**Comment by ikrivosheev** [comment]
Can you run `backlight-notify -b nvidia_0`?

**Comment by coffebar** [comment]
yes, it works
